### ISSUE TITLE
Basic Authentication

### ISSUE THREAD

**Issue by dkhgh** [DefactoSoftware/proof#1]
As a _guest_, I want to be able to **register** and become a _user_. As a _user_ I want to be able to **log in** and **log out**.

**Comment by tarzan** [comment]
NO DEVISE! plz

**Comment by tarzan** [comment]
https://www.google.nl/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=rails%20authentication%20without%20devise
