### ISSUE TITLE
Create an audit trail for evidence

### ISSUE THREAD

**Issue by GlennGeelen** [DefactoSoftware/proof#40]
It should be possible to see what has been done with the evidence, like an issue on github:
<img width="785" alt="screen shot 2015-10-29 at 11 32 15" src="https://cloud.githubusercontent.com/assets/3657171/10816117/c14829e6-7e30-11e5-906f-b89073c569dc.png">

**Comment by alexanderjeurissen** [comment]
I think that an audit log of an evidence isn't really interesting as evidence doesn't change frequent enough to justify a `log`.  as currently only the status of evidence can change.
